### ISSUE TITLE
TreeNode is completely broken

### ISSUE THREAD

**Issue by Yuri6037** [linebender/druid-widget-nursery#114]
Attempting to implement the trait results in:

```
error[E0277]: the trait bound `Span: druid::data::Data` is not satisfied
```

Deriving `Data` has absolutely no effect!

**Comment by Yuri6037** [comment]
Problem solved by cloning and modifying this library locally

**Comment by derekdreery** [comment]
If you fix a bug, please PR the changes. It's very low-effort (basically PRs get merged automatically, I just give them a cursory glance to make sure they're not malicious).

**Comment by Yuri6037** [comment]
The bug is basically that your repository depends on an exact reference of the master branch of druid, whereas in my app I wanted to use latest master.

**Comment by derekdreery** [comment]
Yes the reason for this is so that the ground doesn't move from under people who are developing for `druid-widget-nursery`. It requires fixing your druid to the same hash as the one in the nursery. I wonder if we could do something with features to allow people to drop the specific hash. I'll have a think.
