### ISSUE TITLE
Repository update causes select widget to stop showing subwindow

### ISSUE THREAD

**Issue by giannissc** [linebender/druid-widget-nursery#31]
Upon updating the directory I have noticed that when I click the select button the tooltip (subwindow) does no longer show. I have tried rolling back to the previous release and everything works fine @derekdreery

**Comment by arifd** [comment]
Pinging @Lejero also who made the change.

Btw, having dropdown open a subwindow doesn't work in my tiled window manager (as the windows tile, and don't float). Would it be inconceivably hard to change the approach to dropdowns? (could it `paint_with_z_index` instead?)

**Comment by Lejero** [comment]
One of my PRs updated to a newer version of druid being referenced because there was a problem with the BackgroundBrush type not existing I think, but that's the only thing I can think of that would affect it at all. Otherwise I didn't touch code outside of the ProgressBar, and ProgressBar example. So I guess there might be a drawing change somewhere since druid was last updated?

**Comment by r-ml** [comment]
Both the `select` and `dropdown` examples are broken. \
This happens because the `DROP` notification never reaches [its intended target](https://github.com/linebender/druid-widget-nursery/blob/421a10c949e5457b4131d840bd512b91535c252e/src/dropdown.rs#L52). \
I assume [this PR](https://github.com/linebender/druid/pull/1640) is the culprit after reading the changelog, although I haven't tested reverting it yet.

For now, swapping `submit_notification(DROP)` with `submit_command(DROP)` (and handle that in `dropdown.rs`) is the workaround I'm using.

**Comment by derekdreery** [comment]
Informational post: Under the optimistic merging strategy, commits that partially or fully revert other commits are allowed.

**Comment by jneem** [comment]
@arifd I recently pushed some changes to druid to fix floating windows on tiled window managers (assuming you're using the GTK backend)

**Comment by arifd** [comment]
Druid main, or here in the widget nursery? And excuse my ignorance but when you say "pushed" does that mean the changes are in effect already?

Also, what did the change involve exactly?

Thanks!

**Comment by jneem** [comment]
On the main druid repo, in [#1714](https://github.com/linebender/druid/pull/1714). It doesn't seem to be in effect here yet, because this crate is pinned on an older version of druid...

**Comment by djeedai** [comment]
Note: Just tried the `dropdown` example on Windows and this still doesn't work, even after merging #37.

**Comment by r-ml** [comment]
> Note: Just tried the `dropdown` example on Windows and this still doesn't work, even after merging #37.

Of course, the PR does not touch that example. It fixes the `select` example only. \
You'd need to fix that one as well, see above patch.

BTW, does directing the command directly to the widget any faster, performance wise? I'm not familiar with druid's internals.

**Comment by djeedai** [comment]
I think this is resolved now with the additional fix of #43. @giannissc can you please confirm?

**Comment by giannissc** [comment]
Yeah I can confirm that this has been resolved
